# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Preheim
email: jonathan.preheim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A sample of my projects, writing and experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jpreh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jpreh

# author info
author:
  - name: Jonathan Preheim
  - email: jonathan.preheim@gmail.com
#  - picture: 

# Build settings
markdown: kramdown
#theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Add links to the sidebar
#menu:
#  - title: Resume
#  - url: /resume/
#  - title: Projects
#  - url: /projects/
#  - title: Writing
#  - url: /writing/
#  - title: Experience
#  - url: /experience/

# in footer of every page:
copyright: © 2019. All rights reserved.

# Sidebar image and theme color of the site
accent_image: /assets/img/sidebar-bg.jpg
#accent_color: rgb(79,177,186)

# Hydejack settings:
hydejack:
  no_drawer: true
